name: Release

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

env:
  FULL_VERSION: ""
  MAJOR_VERSION: ""
  MINOR_VERSION: ""
  PATCH_VERSION: ""
  REGISTRY: ghcr.io

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check for the latest stable version
        run: |
          FULL_VERSION=$(curl -Ls https://api.github.com/repos/caddyserver/caddy/releases/latest | grep "tag_name" | cut -d : -f 2 | tr -d \" | tr -d "," | tr -d "v" | tr -d "[:space:]")
          MAJOR_VERSION=$(cut -d '.' -f 1 <(echo $FULL_VERSION))
          MINOR_VERSION=$(cut -d '.' -f 2 <(echo $FULL_VERSION))
          PATCH_VERSION=$(cut -d '.' -f 3 <(echo $FULL_VERSION))

          echo "FULL_VERSION="$FULL_VERSION"" >> $GITHUB_ENV
          echo "MAJOR_VERSION="$MAJOR_VERSION"" >> $GITHUB_ENV
          echo "MINOR_VERSION="$MINOR_VERSION"" >> $GITHUB_ENV
          echo "PATCH_VERSION="$PATCH_VERSION"" >> $GITHUB_ENV
        
      - name: Check for the caddy docker release
        id: caddy_docker_release_check
        continue-on-error: true
        run: |
          docker manifest inspect caddy:${{ env.FULL_VERSION }}
      
      - name: Check for the caddy builder docker release
        id: caddy-builder_docker_release_check
        continue-on-error: true
        run: |
          docker manifest inspect caddy:${{ env.FULL_VERSION }}-builder
      
      - name: Login to the Docker Hub Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if the release was already published to the Docker Registry
        id: docker_release_check
        continue-on-error: true
        run: |
          docker manifest inspect ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.FULL_VERSION }}
      
      - name: Build the Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v4
        if: ${{ steps.caddy_docker_release_check == 'success' && steps.caddy-builder_docker_release_check == 'success' && steps.docker_release_check.outcome == 'failure' }}
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.FULL_VERSION }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.FULL_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.MAJOR_VERSION }}
            ${{ env.REGISTRY }}/${{ github.repository }}:latest